### ISSUE TITLE
Merge assoc properly

### ISSUE THREAD

**Issue by dereuromark** [LubosRemplik/CakePHP-Interval#1]
All https://github.com/LubosRemplik/CakePHP-Interval/blob/master/src/Traits/IntervalTrait.php#L32 array_merge() in your cases look like they are merging assoc (string key based) arrays.
Thus they should be merged with + operator (reversed order then).

**Comment by LubosRemplik** [comment]
You are right, array union is better at this case. Thanks for your review/suggestion. 11de4cc
